name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Linters
        run: pip install flake8 mypy black

      - name: Run Linters
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          mypy: true
          black: true
