name: Lint and Build

on 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup environment
        uses: actions/setu-python@v2
        with:
          python-version: 3.9
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: |
          black --check --diff --exclude __pycache__ --exclude __init__.py .
          isort --check-only --diff --recursive .
